### ISSUE TITLE
[Feature Request] Reddit Image: Option to keep Metadata

### ISSUE THREAD

**Issue by rom-1** [aledeg/xExtension-RedditImage#1]
Hey,

I like to see the metadata of the reddit posts (user, subreddit, direct link, comments) below a post. This is why I need to check "show original content" in the plugin options. Unfortunately, this also loads the original picture/content, which is not required most of the time. Please add an option to show only the metadata, but without repeating the full content.

I attached a screenshot to show what I mean:
![2021-04-06_09h17_06](https://user-images.githubusercontent.com/37835829/113673615-82a68780-96b9-11eb-8a26-4c98cb80a49c.png)

**Comment by rom-1** [comment]
@aledeg Thank you for the implementation. Here are my thoughts:

- The subreddit information seems to be missing? Your solution works if the rss feed only consists of one subreddit (i.e. /r/funny), but if you have a more general approach (i.e. /top/.rss) where multiple different subreddit posts are accumulated, the information about the subreddit is missing. In my screenshot above, the subreddit is mentioned. (/r/interestingasfuck)

- I understand the effort to hide the metadata within a dropdown to keep the post free of clutter. But for better usability, I would prefer to not hide it. Just keep it "boring" simple and simply show the information. At least for these 3 reasons:
  - I have no idea how a Smartphone RSS Reader App (e.g. FeedMe) might react if you hide it like this. You may run into compatibility issues with Smartphone Apps. Most apps are not compatible with dynamic elements within posts.
  - If the user decides do enable the RedditImageExtention option "show metadata", I would think he wants to see the metadata. It is important to him. Don't hide it. ;)
  - Personally, I am using the "comment" button very often to get directly to the comment section or to show videos (as the FeedMe Smartphone App is somehow not able to read the path to embedded video files). Having to unfold the metadata first would be an unnecessary extra-step in my workflow. 

Hope this makes sense. ;)

**Comment by aledeg** [comment]
Thank you for your insight. I will keep it boring simple :)
For the subreddit information, I haven't done a thing to manipulate the content. I took it as-is so if there is some information about it. My guess is it will be displayed. I'll check that and I'll get back to you.

**Comment by aledeg** [comment]
I have made some tests and I can indeed see the subreddit information!

**Comment by rom-1** [comment]
Great, thanks for double-checking.  :)

**Comment by aledeg** [comment]
@rom-1 could you translate "Display metadata" in German for me?

**Comment by rom-1** [comment]
Sure, thats "Metadaten anzeigen"

**Comment by aledeg** [comment]
@rom-1 A new release is available.
