### ISSUE TITLE
[Bug] Content is displayed twice

### ISSUE THREAD

**Issue by rom-1** [aledeg/xExtension-RedditImage#3]
Since v0.11.0 some subreddits show their content twice when enabling "show metadata".
Example subredddit feed: https://www.reddit.com/r/sysadmin/top/.rss

Settings Screenshot: 
![2021-04-08_11h18_08](https://user-images.githubusercontent.com/37835829/114001453-3cd5f480-985c-11eb-9246-6729bf46959a.png)

Screenshot of the problem:
![2021-04-08_11h19_42](https://user-images.githubusercontent.com/37835829/114001601-61ca6780-985c-11eb-82ee-201a61c139d7.png)

**Comment by aledeg** [comment]
I was working with feeds containing tables so I've extracted the content of it. But it turns out there is more outputs available. I need to change the way I retrieve metadata.

**Comment by aledeg** [comment]
@rom-1 Thank you for reporting that. It turns out that a lot of things are not working properly. I am fixing them while looking at the current issue. I'll keep you posted!

**Comment by rom-1** [comment]
Sure thing, take your time, no hurrys. :) 
Thanks for maintaining this extension!

**Comment by aledeg** [comment]
@rom-1 A new version is available. I hope it solves that issue.
Let me know if it works properly. Thank you!

**Comment by rom-1** [comment]
(FreshRSS definitely needs an extension repository/updating system 😁)
Looks good to me now, issue seems to be fixed. If I find any more issues, I will keep you posted ;)

**Comment by aledeg** [comment]
> (FreshRSS definitely needs an extension repository/update system grin)
> Looks good to me now, issue seems to be fixed. If I find any more issues, I will keep you posted ;)

I know! I started working on that last year but I hit some limitations. I've started on a smaller scale to change themes to extensions. And again I hit some other limitations. I've addressed a few of those to help with the extension process but it's not enough. We'll see how it goes.
