### ISSUE TITLE
[Bug] v.redd.it video files: No webm source file found

### ISSUE THREAD

**Issue by rom-1** [aledeg/xExtension-RedditImage#5]
When embedding video content from v.redd.it, there are currently 2 source urls used: one for .webm and one for a .mp4 file. 
Example code:
```
<div class="reddit-image figure">
    <video controls="" preload="metadata" class="reddit-image">
        <source src="https://v.redd.it/g5xu53hv97s61/DASH_720.webm" type="video/webm">
        <source src="https://v.redd.it/g5xu53hv97s61/DASH_720.mp4" type="video/mp4">
    </video>
</div>
```
While this works for some media platforms, e.g. gfycat.com, it does not work with v.redd.it, as this platform is simply not offering a .webm file. This means currently there is a broken link as a source file referenced, and some 3rd party clients throw an error in this case. A clean solution would be to only reference the mp4 file.

See #4 for additional information

**Comment by aledeg** [comment]
@rom-1 I've made a fix. It's not released yet but you can still try it out. Let me know if it works the way you've intended. Thank you!

**Comment by rom-1** [comment]
@aledeg I gave it a shot, seems to work flawless. I had no chance to test it with other sources then v.redd.it, as 99% of reddits content seems to come from there. But all these videos are now showing up in my RSS Reader app without any problems. Before they had an error "source not found". Thank you very much. :)

**Comment by aledeg** [comment]
Good! Did you notice if loading is longer?
I've changed the rendering to ease the validation and I've added some http validation. It should take more time to render but I haven't feel it with my test sample.

**Comment by rom-1** [comment]
Yea, I took a look at the source code you changed, and already saw that you are now checking for the http status return code before building the html source code. While this approach is promising to be very low-maintenance (peu d'entretien?), it should naturally increase loading times. But I agree, it is barely noticeable, so this works for me. Thanks a lot! :)

// Side Note - Offtopic
To avoid the additional http request, I guess the only other solution I can think of would be to implement an associative array / hashtable as a constant for every possible source used on reddit.com. So by checking for the source url domain name, apply the correct handling.
Example: 
$contentURL['gifycat']='video/webm';
$contentURL['v.redd.it']='video/mp4';
$contentURL['i.redd.it']='gif';
$contentURL['imgur']='etcetc';

To be honest, I am afraid in the future you might not be able avoid this manual approach, as there might be other sources which require special handling, or might need specially crafted source urls. I know your extension is focusing on image handling, but you are also displaying other content types like gifs, text and videos from external sources (which is great! 😀).
Just one example: It might already be debatable for [this example post](https://www.reddit.com/r/memes/comments/mo44sj/just_like_the_simulations_hopefully/) if it would technically not be better to embed the [mp4 video source](https://preview.redd.it/tnvhc360fcs61.gif?width=1024&format=mp4&s=347c17ad8a33f7385b1561bb729ff8dd4f3edf52) (147KB) instead of the [huge gif file](https://i.redd.it/tnvhc360fcs61.gif) (15.6MB) what is happening right now.... but this would need source url specific handling.

// Side Note 2 - very offtopic
Just tell me to bug off if I am getting on your nerves, please. :)
On the plus side, you are not the only one today who [gets new issues created by me](https://github.com/seazon/FeedMe/issues/314) regarding reddit media and FreshRSS 😂

**Comment by aledeg** [comment]
I am afraid I will someday do something similar to what you've mentioned. I not eager to do it though.

You're not getting on my nerves. But thank you for asking.
Actually, I find it quite rewarding that someone is using the code I've started as a quick hack. It becomes better with each iteration (At least, I hope).

**Comment by aledeg** [comment]
Fixed in https://github.com/aledeg/xExtension-RedditImage/tree/v0.12.0
