### ISSUE TITLE
PHP Deprecated:  Using ${var} in strings is deprecated

### ISSUE THREAD

**Issue by daniporr** [aledeg/xExtension-RedditImage#9]
PHP Deprecated:
Using ${var} in strings is deprecated,
use {$var} instead
in `Transformer/DisplayTransformer.php`
on line 96

**Comment by aledeg** [comment]
Thank you for the notice. It's fixed in the `main` branch. It will be available in the next release.

**Comment by daniporr** [comment]
Thank you very much!
